  name: Node.js CI

  on: [push]

  jobs:
    build:

      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}

      - name: npm install, build
        run: |
          npm run build-prod
          cd ..
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart

