name: deploy
on: [push]
jobs:
  deploy:

    runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    #- name: Use Node.js ${{ matrix.node-version }}
      uses: appleboy/ssh-action@master
      #uses: actions/setup-node@v2
      with:
        #node-version: ${{ matrix.node-version }}
       # cache: 'npm'
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
   # - run: npm install
    - run: npm start
