name: Node Github CI
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install 
      run: |
        npm install
      env:
        CI: true

  deploy:
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/html/github-ci
          git pull origin master
          sudo /root/.nvm/versions/node/v16.11.0/bin/npm install 
          sudo /root/.nvm/versions/node/v16.11.0/bin/pm2 restart index