name: Node.js CI
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH connection & deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          sudo git pull 
          sudo /root/.nvm/versions/node/v16.11.0/bin/npm install 
          sudo /root/.nvm/versions/node/v16.11.0/bin/pm2 restart all
